name: matthiola_flower_shop
description: "A new Flutter project."
publish_to: 'none'

# version: 1.0.12+14
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  algoliasearch: ^1.28.3
  auto_size_text: ^3.0.0
  bloc: ^8.1.4
  cached_network_image: ^3.4.0
  cloud_firestore: ^5.2.1
  cloud_functions: ^5.0.4
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  firebase_ui_firestore: ^1.7.0
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_blurhash: ^0.8.2
  flutter_native_splash: ^2.4.1
  flutter_svg: ^2.0.10+1
  formz: ^0.7.0
  freezed_annotation: ^2.4.4
  fuzzywuzzy: ^1.2.0
  gap: ^3.0.1
  get_it: ^7.7.0
  go_router: ^14.2.7
  json_annotation: ^4.9.0
  logger: ^2.5.0
  lottie: ^3.1.2
  mailer: ^6.1.2
  multiple_result: ^5.1.0
  mustache_template: ^2.0.0
  octo_image: ^2.1.0
  shared_preferences: ^2.3.2
  side_effect_cubit: ^1.0.1
  slang: ^3.31.1
  slang_flutter: ^3.31.0
  upgrader: 
    git:
      url: https://github.com/SK1n/upgrader.git
      ref: romanian_localization

dev_dependencies:
  build_runner: ^2.4.12
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  go_router_builder: ^2.7.1
  json_serializable: ^6.8.0
  very_good_analysis: ^6.0.0

flutter:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/roboto/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/roboto/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
  uses-material-design: true
  assets:
    - assets/
    - assets/logo/
    - assets/icons/
    - assets/animations/
